### ISSUE TITLE
Scavenging only requires the ops user

### ISSUE THREAD

**Issue by ChrisMcKee** [dotnetmentor/terraform-aws-eventstore#1]
https://github.com/dotnetmentor/terraform-aws-eventstore/blob/7ffd6a29599735aaff27dd0ebb85119b07dcc5a4/modules/scavenging/setup.sh#L32

You can use the ops user to kick off scavenging rather than the admin. 👍

**Comment by ChrisMcKee** [comment]
With the main userscript you're taking in IAM credentials; normally you'd create a policy + iam role and assign that to the EC2 instance. AWS then maintains the env-vars for you using STS. 
If you're following the immutable infrastructure line, it's better to do 99% in packer and the last leg of configuration only via terraform. 
_apologies if im teaching grandmother to suck eggs_

**Comment by kristofferahl** [comment]
@ChrisMcKee Thanks! I'll make sure to change the variable names. Actually think we're using the ops user but the variable names are still wrong.

In regards to IAM credentials. Yep, that's one of the changes I'm looking to make once I find the time. Great to have a reminder here though so I'll leave the issue open until it's been resolved.

Packer is also on the list but a bit lower priority at the moment.

Thanks again!
